apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: app-tg-config
  namespace: edulearn-app
spec:
  targetReference:
    name: edulearn-app-gateway
  defaultConfiguration:
    targetType: ip
