---
# Namespace
fluentbit_namespace: observability

# Helm
fluentbit_release_name: fluent-bit
fluentbit_chart_repo: https://fluent.github.io/helm-charts
fluentbit_chart_name: fluent/fluent-bit
fluentbit_chart_version: "0.50.0"

# Service Account
fluentbit_service_account: fluent-bit

# Collector
otel_collector_host: otel-collector.observability.svc.cluster.local
otel_collector_otlp_port: 4318

# Resources
fluentbit_resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

# Log Level
fluentbit_log_level: info

# Service Monitor
fluentbit_service_monitor_enabled: true

# Labels
prometheus_release_label: kube-prometheus-stack