nameOverride: course

replicaCount: 2

image:
  repository: ghcr.io/muhammed-shafeeque-th/edulearn/course
  pullPolicy: IfNotPresent
  tag: "v1.0.4"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 50053
  ports:
   - name: http
     port: 3003
     targetPort: 3003
   - name: grpc
     port: 50053
     targetPort: 50053

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: api.edulearn.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

livenessProbe:
  httpGet:
    path: /health
    port: 8083 # http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 8083 # http
  initialDelaySeconds: 5
  periodSeconds: 5

env:
  NODE_ENV: "development"
  SERVICE_NAME: course-service
  serviceVersion: "0.0.1"
  API_PORT: 3003
  GRPC_PORT: 50053

configMaps:
  - edulearn-config
  - course-config

secretRefs:
  - edulearn-secrets
  - course-secrets

configData:
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: course_service
  DATABASE_MAX_CONNECTIONS: "50"
  DATABASE_MIN_CONNECTIONS: "10"
  DATABASE_CONNECTION_TIMEOUT: "30000"
  DATABASE_IDLE_TIMEOUT: "10000"

  # KAFKA CONFIGURATION
  KAFKA_CLIENT_ID: course-service
  KAFKA_CONSUMER_GROUP: course-service-group
  KAFKA_MAX_POLL_RECORDS: "100"
  KAFKA_FETCH_MAX_BYTES: "5242880"
  KAFKA_SASL_ENABLED: "false"

  # REDIS CONFIGURATION
  REDIS_DB: "4"
  REDIS_MAX_CONNECTIONS: "100"
  REDIS_MIN_CONNECTIONS: "10"
  REDIS_TTL_DEFAULT: "86400"
  REDIS_KEY_PREFIX: "edulearn:course:"

  # gRPC CONFIGURATION
  GRPC_PORT: "50053"
  GRPC_MAX_CONCURRENT_STREAMS: "100"
  GRPC_MAX_CONNECTION_IDLE: 15s
  GRPC_MAX_CONNECTION_AGE: 30s
  GRPC_MAX_CONNECTION_AGE_GRACE: 5s
  GRPC_TIME: 2h
  GRPC_TIMEOUT: 20s

  # OBSERVABILITY CONFIGURATION

  # OpenTelemetry Jaeger Tracing
  JAEGER_SAMPLING_RATE: "0.1"
  JAEGER_SAMPLING_TYPE: probabilistic

  # Prometheus Metrics
  PROMETHEUS_PATH: /metrics
  METRICS_ENABLED: "true"

  # Logging Configuration
  LOG_LEVEL: debug
  LOG_FORMAT: json
  LOG_FILE: logs/course-service.log
  LOG_OUTPUT: stdout
  LOG_MAX_SIZE: 100m
  LOG_MAX_FILES: "5"
  LOG_COMPRESS: "true"

  # Tracing Configuration
  TRACING_ENABLED: "true"
  TRACING_SAMPLING_RATE: "0.1"
  TRACING_SERVICE_NAME: course-service

  #OTP_TEMPLATE_PATH=app\internal\shared\template\activation-mail.html

  # HEALTH CHECK CONFIGURATION
  HEALTH_PORT: "8083"
  HEALTH_PATH: /health
  READINESS_PORT: "8083"
  READINESS_PATH: /ready
  LIVENESS_PORT: "8083"
  LIVENESS_PATH: /live


secretData: {}

configMounts: []
