cluster_name: edulearn-cluster

aws_region: ap-south-1

aws_account_id: "353452028891"

base_domain: muhammedshafeeque.online

bastion_public_ip: 13.233.50.140

aws_lbc_version: "3.0.0"

certificate_arn: arn:aws:acm:ap-south-1:467008424241:certificate/4172a940-f65e-4496-bcb3-b85b16e3efea

gateway_hostname: "*.muhammedshafeeque.online"

external_dns_domain_filters:
- muhammedshafeeque.online

external_dns_txt_owner_id: edulearn-dev

github_repo: https://github.com/muhammed-shafeeque-th/Edulearn-platform

git_revision: main

argocd_hostname: argocd.{{base_domain}}

argocd_images:

- alias: gateway
  repository: ghcr.io/muhammed-shafeeque-th/edulearn/gateway

- alias: auth
  repository: ghcr.io/muhammed-shafeeque-th/edulearn/auth

- alias: user
  repository: ghcr.io/muhammed-shafeeque-th/edulearn/user

- alias: course
  repository: ghcr.io/muhammed-shafeeque-th/edulearn/course

- alias: notification
  repository: ghcr.io/muhammed-shafeeque-th/edulearn/notification

- alias: payment
  repository: ghcr.io/muhammed-shafeeque-th/edulearn/payment

- alias: order
  repository: ghcr.io/muhammed-shafeeque-th/edulearn/order

- alias: chat
  repository: ghcr.io/muhammed-shafeeque-th/edulearn/chat

eks_cluster_endpoint: https://444DC081388761A25E1C81B2D8A8AA1A.gr7.ap-south-1.eks.amazonaws.com
vpc_id: vpc-052b61aa181c6fb1f
loki_bucket: edulearn-loki-bucket
tempo_bucket: edulearn-tempo-bucket

alertmanager_secret_name: alertmanager-config

