apiVersion: v2
name: redis
description: Redis wrapper using Bitnami chart
type: application
version: 1.0.1
appVersion: "1.0.1"

dependencies:
  - name: redis
    version: 27.0.15
    repository: https://charts.bitnami.com/bitnami
    alias: redis