enabled: true

redis:
  architecture: standalone

  auth:
    enabled: false

  master:
    persistence:
      enabled: true
      # storageClass: gp3
      # size: 8Gi

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

  replica:
    replicaCount: 0

  commonConfiguration: |-
    appendonly yes
    save 60 1000

  networkPolicy:
    enabled: false

  metrics:
    enabled: false