---

- name: Create External DNS Operator ServiceAccount
  kubernetes.core.k8s:

    state: present

    definition:

      apiVersion: v1

      kind: ServiceAccount

      metadata:

        name: "{{ external_dns_sa }}"

        namespace: "{{ external_dns_namespace }}"