apiVersion: v2
name: postgres
description: PostgreSQL using Bitnami chart
type: application
version: 1.0.1
appVersion: "1.0.1"

dependencies:
  - name: edulearn-common
    version: 1.0.1
    repository: file://../../edulearn-common
    
  - name: postgresql
    version: 18.7.13
    repository: https://charts.bitnami.com/bitnami
    alias: postgresql