FROM node:22.17.1-alpine3.22

RUN apk update && \
    apk upgrade --no-cache
    
LABEL org.opencontainers.image.title="EduLearn Node Base"

ENV NODE_ENV=production

WORKDIR /app

RUN corepack enable

# Install build essentials (for native deps like bcrypt)
RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    libc6-compat

RUN addgroup -S edulearn \
 && adduser -S edulearn -G edulearn