---
- name: Install prerequisites
  ansible.builtin.import_tasks: prerequisites.yml

- name: Crate cluster role and bind it to otel-sa
  ansible.builtin.import_tasks: rbac.yml

- name: Install OpenTelemetry Collector
  ansible.builtin.import_tasks: install.yml

- name: Verify deployment
  ansible.builtin.import_tasks: verify.yml

- name: Deployment summary
  ansible.builtin.import_tasks: summary.yml