
apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: edulearn
spec: 
  selector:
    app: user-service
  ports:
    - name: grpc
      port: 50052
      targetPort: 50052
    - name: http
      port: 3002
      targetPort: 3002
  type: ClusterIP


