apiVersion: v2
name: notification
description: notification for EduLearn
type: application
version: 1.0.2
appVersion: "1.0.2"
dependencies:
  - name: edulearn-common
    version: 1.0.1
    repository: file://../../../edulearn-common