---
- name: Download kubectl for EKS
  get_url:
    url: https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.0/2024-05-29/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Verify kubectl
  command: kubectl version --client
  register: kubectl_version
  changed_when: false
