apiVersion: v1
kind: Service
metadata:
  name: payment-svc
  namespace: edulearn
  labels:
    app: payment-svc
spec:
  selector:
    app: payment-service
  ports:
    - name: grpc
      port: 50055
      targetPort: 50055
      protocol: TCP
    - name: webhook
      port: 4005
      targetPort: 4005
      protocol: TCP
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: metrics
      port: 9091
      targetPort: 9091
      protocol: TCP
  type: ClusterIP