apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: payment-service-network-policy
  namespace: edulearn
spec:
  podSelector:
    matchLabels:
      app: payment-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: edulearn
      ports:
        - protocol: TCP
          port: 50051 # gRPC
        - protocol: TCP
          port: 3000 # HTTP (webhooks)
        - protocol: TCP
          port: 9091 # Metrics
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: edulearn
      ports:
        - protocol: TCP
          port: 5432 # PostgreSQL
        - protocol: TCP
          port: 6379 # Redis
        - protocol: TCP
          port: 9092 # Kafka
        - protocol: TCP
          port: 3100 # Loki (logging)